### ISSUE TITLE
queue: implement a queue so number of instantiated RWE_ can be limited

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana#119]
As described in https://github.com/reanahub/reana/issues/118, we are moving to an architecture where workflow engines are instantiated on demand. We need to take care now of how many engines we are spawning since we could overload the cluster.

**Comment by dinosk** [comment]
A workflow submission queue could be used to prioritize and set limits on the workflows running on the platform. This queue is not meant to overlap with k8s' internal queue, rather it would be acting as a buffer enabling:

1. throttling & prioritization of jobs based on policies and [PodPriorities](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/)
2. providing information on waiting time, platform resource capacity
3. maintaining workflow submission info until successful execution

The queue can be held in RabbitMQ, as it is currently included in REANA, and an intermediary simple scheduler will submit, in turn, workflows to R-Server to follow the usual flow.
![workflow-queue 1](https://user-images.githubusercontent.com/1566093/50085916-c54ba980-01fb-11e9-9822-bcf426e225ff.png)

**Comment by tiborsimko** [comment]
Regarding sequence diagram, `REANA-Server` would accept the submission and set the status to `queued` (if busy) or `started` (if possible to run it immediately).  We may need another state with its state-machine-governed allowed/disallowed transitions...

**Comment by dinosk** [comment]
Queue implemented in merged PRs, closing.
