### ISSUE TITLE
make: include all examples when using `ci` option

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana#147]
When releasing new REANA versions, we test that all our working examples continue to work after the release.

To ease this task, we can add an option to run all working examples with the [`ci` target](https://github.com/reanahub/reana/blob/master/Makefile#L96).

**Comment by tiborsimko** [comment]
... which could be done best by enriching `reana-dev` to have something like:

```console
$ reana-dev run-example -c ALL
```

so that it is usable also outside of the `Makefile` context.

**Comment by diegodelemos** [comment]
Would it be of interest having an option to run only hello world by default and only if requested all the examples? If one day we would like to plug it to Travis on every PR, it would be faster with only hello world, but for nightlies, it would be better to test everything.

If not we can just live with the [`reana-dev run-example -c ALL`](https://github.com/reanahub/reana/issues/150) and here we always call "all".
