### ISSUE TITLE
docs: General development instructions for REANA components

### ISSUE THREAD

**Issue by hjhsalo** [reanahub/reana#16]
**In order to develop REANA components you need to somehow create pods based on the new, development time Docker images in your Kubernetes cluster.**

Current install / instantiation scripts make Kubernetes pull the images of each REANA component from Docker Hub.

Of course one could push development time images to Docker Hub, but at least my opinion is that is should only contain images that are known to work (development time images might not) and released through proper release process.

To support development efforts, we probably should specify, or at least say a thing or two about the process of updating the Kubernetes cluster with a new image without pushing it to Docker Hub.

With Minikube, which I presume we would use and recommend for local development environment, you have couple of options:

**1. Use local cache of Docker daemon running inside Minikube VM and update pod(s) by deleting previous pod(s) or by triggering a rolling update for Kubernetes cluster**
- Attach your Docker client to Docker daemon running in Minikube VM:
  ```eval "$(minikube docker-env)"```

- Build your Dockerfile (e.g. ```docker build . -t reana-message-broker```).
  Name it according to REANA component naming schema (e.g. 'reana-message-broker').
  Don't [tag](https://docs.docker.com/engine/reference/commandline/build/#tag-an-image--t) the image in the build command. (e.g. ```docker build . -t reana-message-broker:development```)
  The built, _new_ image gets stored to local cache of Docker daemon running in Minikube VM.

- Delete the existing pod which is based on the _old_ Docker image:
  ```kubectl delete pods <POD_NAME>``` , where <POD_NAME> is e.g. 'message-broker-1410199975-gtcr8'
  (You can list pods with ```kubectl get pods```)
  When Kubernetes sees that the pod is destroyed, it will create a new pod, using the latest image it has available either in a) local cache or in b) Docker registry specified to it (defaults to Docker Hub). In this case it ~will~ should use the _new_ image from local cache.
  Alternatively you can trigger a [rolling update](https://kubernetes.io/docs/tasks/run-application/rolling-update-replication-controller/) for all of the REANA components deployed in Kubernetes cluster, which will re-create the pods using latest available images. Kubernetes ~will~ should use the _new_ image from local cache.

- Optionally you can check that the new pod was created based on the _new_ image by comparing sha256 digest of the image reported by Docker client and sha256 digest of a pod's image reported by Kubernetes:
    - ```docker images --no-trunc reana-message-broker```
      --> ```sha256:ec7b2076d2744361332be1397224025456910feb83d41fcc4ab8e409bab5cf6a```
    - ```kubectl describe pod message-broker- | grep Image```
      --> ```Image ID:		docker://sha256:6a5233dac19eb8e24445cda16fcb7ab4bfaca4d32f1cad0f6701c4060a184987```

- Note: If ```imagePullPolicy: IfNotPresent``` or ```imagePullPolicy: Never``` is not explicitly used in Kubernetes manifest file, this method is going to fail. Currently the manifests of each REANA component specify ```imagePullPolicy: IfNotPresent```. Kubernetes seems to default to ```imagePullPolicy: Always```
  _"By default, the kubelet will try to pull each image from the specified registry. However, if the imagePullPolicy property of the container is set to IfNotPresent or Never, then a local image is used (preferentially or exclusively, respectively)."_ (https://kubernetes.io/docs/concepts/containers/images/#pre-pulling-images)

**2. Use local Docker registry and use "imagePullPolicy: Always" -policy for the deployment of REANA components in Kubernetes cluster. Update pod(s) by deleting previous pod(s) or by triggering a rolling update for Kubernetes cluster**

- Create a [local Docker registry](https://docs.docker.com/registry/deploying/). (e.g. ```docker run -d -p 5000:5000 --restart=always --name registry registry:2```)
  Optionally prepopulate it with Docker images of REANA components from Docker Hub:
  ```docker pull reanahub/reana-message-broker```
  ```docker tag reanahub/reana-message-broker localhost:5000/reana-message-broker```
  ```docker push localhost:5000/reana-message-broker```

- When starting Minikube specify that you want to use a private / custom Docker registry for the images. (e.g. ```minikube start --insecure-registry localhost:5000```)

- Build your Dockerfile (e.g. ```docker build . -t reana-message-broker```).
  Name it according to REANA component naming schema (e.g. 'reana-message-broker').
  Don't [tag](https://docs.docker.com/engine/reference/commandline/build/#tag-an-image--t) the image in the build command. (e.g. ```docker build . -t reana-message-broker:development```)

- Push the _new_ image to your local Docker registry (e.g. ```docker push localhost:5000/reana-message-broker```)

- Delete the existing pod which uses the _old_ image.
  When Kubernetes sees that the pod is destroyed, it will create a new pod, using the latest image it can find from the local Docker registry. In this case it ~will~ should use the _new_ image from local Docker registry.
  Alternatively you can trigger a [rolling update](https://kubernetes.io/docs/tasks/run-application/rolling-update-replication-controller/) for all of the REANA components deployed in Kubernetes cluster, which will re-create the pods using latest available images. Kubernetes ~will~ should use the _new_ image from local Docker registry.

- Optionally you can check that the new pod was created based on the _new_ image by comparing sha256 digest of the image reported by Docker client and sha256 digest of a pod's image reported by Kubernetes:
    - ```docker images --no-trunc reana-message-broker```
      --> ```sha256:ec7b2076d2744361332be1397224025456910feb83d41fcc4ab8e409bab5cf6a```
    - ```kubectl describe pod message-broker- | grep Image```
      --> ```Image ID:		docker://sha256:6a5233dac19eb8e24445cda16fcb7ab4bfaca4d32f1cad0f6701c4060a184987```

- Note: This method ~will~ might fail if ```imagePullPolicy: IfNotPresent``` is used and image available from local cache of Docker daemon running in Minikube VM is newer than the one available from local Docker registry. Also ```imagePullPolicy: Never``` won't work.

**Things to consider**:

- I don't know if both or even on of the methods would work on a "real" Kubernetes cluster the same way as they work on Minikube (should, but you never know without trying), or what kind of configuration efforts you need to do e.g. to specify Docker registry to use for a deployment of REANA component to Kubernetes cluster that you are not administrating (might not even be possible).

- Docker instructions are not that clear on what is considered to be the latest image.
  Somewhere I read that if you already have an image in registry (or in local cache) and you build another image with the same name and in the build command specify a tag for it, this new image is not considered to be the latest image!!
  It will be considered to be latest image if you don't specify tags in the build command itself, and tag the image after building with a completely separate ['docker tag' command](https://docs.docker.com/engine/reference/commandline/tag/). (e.g. ```docker tag reana-message-broker reana-message-broker:development```
  Docker seems to tag ':latest' automatically if don't specify a tag in the build command.
  I don't (yet) know if the image is considered to be the latest if one specifies ':latest' tag in the build command. (e.g. ```docker build . -t reana-message-broker:latest```)
  This ambiguity affects both of the previously described methods, at least when developer tags the image in the actual build command without providing also the ':latest' tag.

**Comment by hjhsalo** [comment]
Here is a quick draft for instructions for option 1:

---

### How to update Docker image of any REANA component inside Minikube (or full Kubernetes cluster)
0. Setup a local deployment of REANA (https://github.com/reanahub/reana)

1. Clone the repo of the REANA component you wish to build / develop / test. Make some changes and commit.

2. Connect Docker client to Minikube VM's Docker daemon:
  ```$ eval "$(minikube docker-env)"```

3. [OPTIONAL] Check that you are really connected to Minikube VM's Docker daemon
* There should be at least a bunch of gcr.io/google-containers/*** -images listed
  ```$ docker images | grep gcr.io```

4. Build new Docker image for the REANA component you are developing
  ```$ docker build . -t reana-message-broker```
  
5. [OPTIONAL] Tag the new image e.g. with latest git commit hash
  ```$ docker tag reana-message-broker reana-message-broker:<TAG> (where <TAG> e.g. '$(git log --pretty=format:'%h' -n 1)')```

6. [OPTIONAL] Note down the sha256 digest of image
* (In case you want to later double check the new pod is created from this new image)
  ```$ docker images --no-trunc reana-message-broker```

NOTE: Minikube will get the latest image it can found 1)locally inside Minikube VM's Docker daemon cache or 2)specified Docker registry (defaults to Docker Hub)

7. Destroy previous pod
  ```$ kubectl delete pods <POD_NAME>``` (where <POD_NAME> e.g. 'message-broker-1410199975-gtcr8')

8. [OPTIONAL] Check pod status in Minikube.
* Check that new pod has been started (check the 'AGE' -column).
* Old pod might be in status 'Terminating'.
  ```$ kubectl get pods```

9. [OPTIONAL] Check that the new pod is actually created from you new image
* Run a shell and e.g. grep for your changes?
  ```$ kubectl exec -it <POD_NAME> -- /bin/sh```

* Describe the new pod and compare digest of the image used to build the new pod to digest of the new image you build in step 4.
  ```$ kubectl describe pod message-broker- | grep Image```
  
* Describe the cluster and make sure that pods for the component you are developing are created from image that has the tag you specified in step 5.
  ```$ kubectl describe pod message-broker-```

---

### Misc / Troubleshooting:

* How to init REANA cluster a second time?
  ```$ eval "$(minikube docker-env -u)"```
  ```$ minikube delete```
  ```$ minikube start```
  ```$ eval "$(minikube docker-env)"```

* Bind Docker client to Docker daemon running inside Minikube VM
  ```$ eval "$(minikube docker-env)"```

* Remove Docker client binding to Docker daemon running inside Minikube VM
  ```$ eval "$(minikube docker-env -u)"```
  
* Create and run Minikube VM-cluster
  (In case the VM-cluster is not running and Minikube has been properly installed, e.g. with 'reana install-minikube')
  ```$ minikube start```

* Delete Minikube VM-cluster
  ```$ minikube delete```
  
* Additionally delete also the Minikube resources in local system
  ```$ rm -rf ~/.minikube```

* Delete pods of REANA components without deleting Minikube VM
  $ kubectl delete -Rf configuration-manifests

**Comment by tiborsimko** [comment]
We mostly all use "kill pod" technique to get refreshed content, i.e. the option 1 above.

It would be good to clean the musings behind option 1 and commit them to the central REANA "Developer guide".

**Comment by tiborsimko** [comment]
The "delete pod" technique has been decumented; closing.
