### ISSUE TITLE
docs: doc build status badges are not showing the actual state

### ISSUE THREAD

**Issue by okraskaj** [reanahub/reana#162]
The docs badges in docs and READMEs are pointing to a wrong url, so it looks like doc builds are always passing.

This is an issue in most of the components, and the link is:
```https://readthedocs.org/projects/docs/badge/?version=latest ``` 
whre it should be
```https://readthedocs.org/projects/$PROJECT_NAME/badge/?version=latest```

**Comment by tiborsimko** [comment]
Note also that I'm changing RTFD settings everywhere to:
- [ ] switch to Python 3 (except perhaps for r-w-e-y that requires Python 2.7 still...)
- [ ] kill EPUB/PDF formats
