### ISSUE TITLE
make: add option to build/deploy with the UI component

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana#194]
Add a [new configuration](https://github.com/reanahub/reana/blob/245559c72206ec0414dd2fe025e68ca9cde25447/Makefile#L43-L53) to choose if the REANA UI should be built and deployed. By default, it shouldn't do it since it is only ready for CERN.

Currently, it is built by default but never deployed.

**Comment by tiborsimko** [comment]
Note that we may want to amend `cli.py` and `REPO_LIST_CLUSTER` as well, so that the component wouldn't be built unnecessarily.  (E.g. currently I've commented `reana-ui` out there in order to speed up local  developments.)
