### ISSUE TITLE
cernopendata: scalability

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana#244]
Test whether ~30 people can read Htt open datasets from [CERN Open Data portal](http://opendata.cern.ch/)
(via EOSPUBLIC and/or via COD cache). A user storm simulated in the past using [Locust](https://locust.io/), see [results](https://github.com/cernopendata/opendata.cern.ch/issues/2026) and implementation [PR](https://github.com/cernopendata/opendata.cern.ch/pull/2214). We just need to create new scenarios adapted to the usage we will have during the workshop.

**Comment by tiborsimko** [comment]
Tested workflow for ~35 concurrent users, everything was OK.

The workshop will use 10x reduced datasets hosted elsewhere on EOS, so we can close this issue.
