### ISSUE TITLE
devops: basic cluster monitoring

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana#251]
Get ready for quick monitoring and resolution for failed workflows.  For example, a snapshot from production cluster today:

```console
$ kubectl get pods
NAME                                                      READY   STATUS    RESTARTS   AGE
batch-serial-21a304f9-f955-4c70-98db-e04794279fde-d2v6s   1/2     Running   0          7d17h
batch-serial-f699e6f2-e26c-40e1-96c6-ae8105c7cd55-9sg9q   1/2     Running   0          3d
batch-yadage-632a68c9-00c2-43af-af12-263e2d0cdec2-cfrxt   1/2     Running   0          7d17h
batch-yadage-a72c3d98-9744-4d77-ac3f-0583d6586506-z5z9x   1/2     Running   0          7d17h
batch-yadage-f2e9f2a3-46df-4de8-bddf-8991bc8caa72-4vzlb   1/2     Running   0          3d
cache-f74dd5fd8-rrwcg                                     1/1     Running   0          9d
d92872ad-e85d-4b5c-aa31-ecb361e23d8b-xm9ps                0/1     Error     0          42h
db-6f8f8579c9-hv427                                       1/1     Running   0          9d
message-broker-789ff97759-hnjvc                           1/1     Running   0          9d
server-76d6b4d68c-s7h7c                                   2/2     Running   0          9d
ui-59884b5965-kw8nt                                       1/1     Running   0          9d
workflow-controller-7d75898f5d-knllj                      2/2     Running   0          9d
```

- Are Graphana instances up and running? No? Then fix them following [official docs](https://clouddocs.web.cern.ch/containers/tutorials/monitoring.html)
  - [x] http://reana-dashboard.cern.ch/
  - [x] http://reana-qa-dashboard.cern.ch/
  - [x] http://reana-dev-dashboard.cern.ch/
- Configure alerts is it quick? https://clouddocs.web.cern.ch/containers/tutorials/prometheus.html yes? then we do it, otherwise the quickest solution
- Configure metrics is it quick? https://clouddocs.web.cern.ch/containers/tutorials/prometheus.html yes? then we do it, otherwise the quickest solution

Note: Error pods not garbage-collected, workflows apparently still running, etc.

**Comment by diegodelemos** [comment]
For now, we will be able to use Grafana and the Kubernetes dashboard, documented in https://digital-repositories.web.cern.ch/digital-repositories/reana/operations#monitoring ✅

Creation of new Grafana dashboards can be done later as it is a well-isolated task ⏳

@roksys @tiborsimko @mvidalgarcia also, as it is documented in the internal docs, we have a central user for Grafana... we could explore the possibility of having one user per person... but that could also be messy as this is not integrating with central egroups or users, WDYT?

**Comment by mvidalgarcia** [comment]
> @roksys @tiborsimko @mvidalgarcia also, as it is documented in the internal docs, we have a central user for Grafana... we could explore the possibility of having one user per person... but that could also be messy as this is not integrating with central egroups or users, WDYT?

As long as we have the secrets on `tbag` or similar it's ok for me.

**Comment by diegodelemos** [comment]
Closing as basic monitoring is up and running.
