### ISSUE TITLE
config: allow toggling garbage collection of finished workflows/jobs

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana#280]
Currently, if a job/workflow is finished, the pods are cleaned out, in [RJC for jobs](https://github.com/reanahub/reana-job-controller/blob/84181974db90ffe451acedab129f7a9ede3223d6/reana_job_controller/job_monitor.py#L164) and in [RWC for workflows](https://github.com/reanahub/reana-workflow-controller/blob/274aed1007e7b3a21334b6654b8b720aa9fd1d24/reana_workflow_controller/consumer.py#L89-L91). This makes it nearly impossible to find out what went wrong if a job fails with no logs.

We shall introduce a new config, and either turn it off when debug mode is on (`debug.enabled=true`) or have a new separate config in `values.yaml`.

**Comment by tiborsimko** [comment]
It might be useful to go for the second option, i.e. new separate TTL configuration variable for this, so that if something strange happens on a REANA production site, the admins could inspect problems with faliing pods without switching to the full debugging mode.

**Comment by diegodelemos** [comment]
CCing @khurtado as he might be interested in following this up.

**Comment by diegodelemos** [comment]
Closing as this is included as part of https://github.com/reanahub/reana/issues/461.
