### ISSUE TITLE
frontend: run security scans

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana#302]
Run usual web security scanning of REANA front end services and nodes (UI, REST API).

Tools: skipfish, w3af, nessus.

Example:

```
$ skipfish -m 4 -s 20000 -Y -o /tmp/skipfishresults http://localhost/
```

**Comment by tiborsimko** [comment]
LGTM (after putting proper SSL)

**Comment by diegodelemos** [comment]
I believe we can close this issue @tiborsimko.
