### ISSUE TITLE
release: Helm release missing from index.yaml

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana#314]
The release `0.7.0-dev20200520`  is not present in https://reanahub.github.io/reana/index.yaml however we can find it in the repository releases https://github.com/reanahub/reana/releases.

This needs to be fixed as the Helm executable relies on `index.yaml` to fetch the latest release.

**Comment by diegodelemos** [comment]
This specific case has been addressed in https://github.com/reanahub/reana/pull/316 by releasing manually. The problem is that [we are using on tag push event](https://github.com/reanahub/reana/blob/5e79d0073f96dbdbc5deb86805f8c3f472d4f780/.github/workflows/helm-releaser.yaml#L6) and we were pushing the tags `reana-X.Y.Z | reana-X.Y.Z-devYYYYMMDD` which is what [Chart Releaser](https://github.com/helm/chart-releaser) relies on, so:
1. We push the tag
2. The GitHub action runs
3. [Chart Releaser detects no changes](https://github.com/reanahub/reana/runs/705511779?check_suite_focus=true#step:4:9) as the tag is already created

Some real solutions:
- Trigger manually
- Push two tags: one tag to trigger the GitHub actions, second tag with the format previously stated which will be created by Chart Releaser
- Others? [Here](https://help.github.com/en/actions/reference/events-that-trigger-workflows) the list of possible events that can trigger GitHub Actions workflows

P.S.: It wasn't straight forward to come to this conclusion as GitHub actions, contrary to Travis CI or REANA, do not have a notion of history of previous workflow runs for a single workflow/commit/pull request/branch, one can see the history of different workflow/commit/pull request/branch.

**Comment by mvidalgarcia** [comment]
I would also go for **(b)**. It might seem that we're triggering too many releases but I think it's because we're in a helm *early stage*. I want to think that in the future our charts will be more stable and won't trigger so many GitHub Actions workflows.
