### ISSUE TITLE
scripts: `reana down` does not destroy shared folder

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana#32]
`reana down` should also destroy the shared `/reana` folder on the minikube VM, otherwise people doing  `reana down && reana init` would get into the problem described in https://github.com/reanahub/reana-workflow-controller/issues/33

Is the word "down" sufficiently strong to express the meaning that everything will be deleted forever?

Shall we take inspiration from docker-compose and accept this and also introduce some softer "up", "stop" commands?

Shall we take inspiration from vagrant and require a stronger word "vagrant destroy"? 

Shall we take inspiration from minikube and require a stronger word "minikube delete" and introduce a softer command "stop"?

**Comment by diegodelemos** [comment]
The `reana` command doesn't exist anymore. We do a deletion of the workspace in the Makefile's teardown target, https://github.com/reanahub/reana/blob/96d686060fe3d579e5391951737b8187863f9fe5/Makefile#L185.
