### ISSUE TITLE
docs: reana-cluster

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana#34]
Update "Getting started" docs following up the release of `reana-cluster`. https://github.com/reanahub/reana-cluster/issues/3

**Comment by hjhsalo** [comment]
REANA system --> REANA cloud
`reana get`, `reana init`, etc. --> `reana-cluster get`, `reana-cluster init`

Let's refer to REANA cloud when writing to end-users.
Let's refer to REANA cluster when writing to developers.
