### ISSUE TITLE
cluster: move to Python-3.8

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana#352]
This is a meta-issue to migrate all REANA cluster components from Python-3.6 to Python-3.8.

Current status:

```console
$ grep python:3.6 r*/Dockerfile
reana-job-controller/Dockerfile:FROM python:3.6-slim
reana-server/Dockerfile:FROM python:3.6-slim
reana-workflow-controller/Dockerfile:FROM python:3.6-slim
reana-workflow-engine-cwl/Dockerfile:FROM python:3.6-slim
reana-workflow-engine-serial/Dockerfile:FROM python:3.6-slim
reana-workflow-engine-yadage/Dockerfile:FROM python:3.6-slim
```

The goal:

- All components will start from python:3.8-slim image.

Things to check for:

- The docker base image change could bring or remove some system dependencies, so `apt-get` commands may need to be updated.

- Python 3.8 may break some of our Python app code, so it may need to be amended.

- Check the old size of e.g. `reana-server` docker image (e.g. 580MB) and the new size, just to see whether our Docker images are still slim; they should be about the same size.

- `.travis.yml` to be updated to use Python 3.8.

- `setup.py` to be updated to declare Python 3.8.

- `setup.py` may need to be updated as to the lowest versions of various dependency packages.

- `requirements.txt` needs to be updated afterwards to propagate these changes (via `pip-compile`).

**Comment by alintulu** [comment]
I checked the size and they are all in the same size order as before

| image | py36 | py38 |
|--- | --- | --- |
| r-w-e-serial | 245MB | 270MB |
| r-w-e-cwl | 493MB | 506MB |
| r-w-e-yadage | 822MB | 835MB |
| r-server | 585MB | 598MB |
| r-j-controller | 668MB | 702MB |
| r-w-controller | 508MB | 522MB |
