### ISSUE TITLE
docs: "getting started with development" -instructions

### ISSUE THREAD

**Issue by hjhsalo** [reanahub/reana#36]
Currently docs are mostly written for end-users that use `reana-client` to interact with REANA cloud.

There is a getting started with development section, but it focuses on bringing up REANA cluster.
It might be beneficial to add more detailed development instructions or direct the user to REANA cluster documentation and write development instructions there.

**Comment by diegodelemos** [comment]
Closed by https://github.com/reanahub/reana/pull/135 (introduces Makefile and usage instructiongs).
