### ISSUE TITLE
reana get reana-workflow-controller does not return a URL

### ISSUE THREAD

**Issue by mr-c** [reanahub/reana#38]
```
$ reana get reana-workflow-controller
127.0.0.1:NodePort:                 http  30226
```
But the docs assume that it does:

```
# check workflows:
curl "http://$(reana get reana-workflow-controller)/api/workflows"
{
  "message": "An organization should be provided"
}
```

**Comment by mr-c** [comment]
Here's a workaround for now:

`reana get reana-workflow-controller | awk ' { print $2"://"$1$3 }' | sed 's/:NodePort//'`

**Comment by tiborsimko** [comment]
@hjhsalo Is the `NodePort` issue still the case with `reana-cluster`?  Anyway the documentation has been updated and we have a dedicated issue for better cluster status reporting (e.g. https://github.com/reanahub/reana-cluster/issues/8) so that we can probably close this one...
