### ISSUE TITLE
cli: exclude components option not working properly

### ISSUE THREAD

**Issue by audrium** [reanahub/reana#395]
While running this command (note `--exclude-components=r-ui`):
`reana-dev run-ci -m /var/reana:/var/reana --exclude-components=r-ui,r-a-vomsproxy,r-a-krb5 -c r-d-helloworld` 

I got an error:
```
Error: timed out waiting for the condition
[2020-09-04T11:14:18] reana: Command 'cat <<EOF | helm install reana helm/reana -n default --create-namespace --wait -f -
components:
  reana_job_controller:
    image: reanahub/reana-job-controller
  reana_message_broker:
    image: reanahub/reana-message-broker
  reana_server:
    image: reanahub/reana-server
  reana_ui:
    image: reanahub/reana-ui
  reana_workflow_controller:
    image: reanahub/reana-workflow-controller
  reana_workflow_engine_cwl:
    image: reanahub/reana-workflow-engine-cwl
  reana_workflow_engine_serial:
    image: reanahub/reana-workflow-engine-serial
  reana_workflow_engine_yadage:
    image: reanahub/reana-workflow-engine-yadage

EOF' returned non-zero exit status 1.
```

`kubectl get pods` returned 
`reana-ui-69f44d96b7-thbtz                    0/1     ImagePullBackOff   0          8m29s`

It worked fine with included `r-ui`:
`reana-dev run-ci -m /var/reana:/var/reana --exclude-components=r-a-vomsproxy,r-a-krb5 -c r-d-helloworld`

**Comment by mvidalgarcia** [comment]
My bad, we need to propagate the excluded components to [`cluster-deploy`](https://github.com/reanahub/reana/blob/master/reana/reana_dev/run.py#L206-L207) call.
