### ISSUE TITLE
util: create a script to populate DB with quota info

### ISSUE THREAD

**Issue by mvidalgarcia** [reanahub/reana#415]
The script can be written in Python and executed in `reana-server`. It should create enough data to test our tasks. Some objects it can create (make sure to not double create them, i.e. create `if not exists`):

[`Resource`](https://github.com/reanahub/reana-db/blob/63dc70464cf05e5337cb0c29826807bc2d4895bf/reana_db/models.py#L513):
- CPU
- HDD

[`ResourceUser`](https://github.com/reanahub/reana-db/blob/63dc70464cf05e5337cb0c29826807bc2d4895bf/reana_db/models.py#L530):
- Iterate over all users and set some sensible `quota_used` and `quota_limit`.

**Comment by diegodelemos** [comment]
This could be implemented as new command in [`reana-db` CLI](https://github.com/reanahub/reana-db/blob/master/reana_db/cli.py) e.g. `reana-db quotas init`. Then added as a new instruction in [R-S's `create-database.sh`](https://github.com/reanahub/reana-server/blob/master/scripts/create-database.sh) so this would [work out of the box with `reana-dev run-ci`](https://github.com/reanahub/reana/blob/2b2cb5a8845e87f56a5e9bd389dca4e5db62caa4/scripts/create-admin-user.sh#L34).
