### ISSUE TITLE
cli: `reana-dev python-unit-tests` broken

### ISSUE THREAD

**Issue by mvidalgarcia** [reanahub/reana#434]
Due to missing Postgres env vars, container initialization and so on.

This command was originally created to run it every time we made changes to the shared modules (`r-commons`, `r-db` and `pytest-reana`) but we tend to forget it.

The idea was including this in the GitHub PR template of the aforementioned modules so we remember to run it and thus avoid side-effects, should we revive this idea?

**Comment by tiborsimko** [comment]
Which component was this broken for? 

It works for me e.g. for r-w-controller recently:

```console
$ cd reana-workflow-controller
$ reana-dev python-unit-tests -c . 
...
======================================================================================= 66 passed, 2 xfailed, 2 xpassed, 2 warnings in 53.29 seconds ========================================================================================
[2021-08-04T14:44:41] reana-workflow-controller: rm -rf ~/.virtualenvs/_reana-workflow-controller
[2021-08-04T14:44:41] : docker stop postgres__reana-workflow-controller
postgres__reana-workflow-controller
```

Perhaps we can close the issue, if it is working for you?

**Comment by mvidalgarcia** [comment]
I don't remember exactly what was happening but it seems to be working now. I could execute it with no issues.
