### ISSUE TITLE
wiki: update CI build links

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana#435]
Update CI build links in https://github.com/reanahub/reana/wiki

Introduce `maint-0.7` and `master` instead of only one `Build` column.

**Comment by tiborsimko** [comment]
Also, check and complete the repository list.  E.g. `reana-auth-*` helper sidecards are missing there. E.g. `reana-cluster` was deprecated and can be removed from the wiki list.

**Comment by mvidalgarcia** [comment]
The page now updated pointing to GH actions and `codecov`: https://github.com/reanahub/reana/wiki

🆕  I've created a script to generate the build status page: [reana_build_status.py](https://gist.github.com/mvidalgarcia/919e5ff3b056c98a4a3f04ee400c7c67#file-reana_build_status-py). Let me know if we want to store this somewhere else.

**Comment by tiborsimko** [comment]
What about putting the code into a new `reana-dev` command? E.g. `reana-dev wiki-create-build-status-page`? Could be useful for later, we might be expanding wiki with other developer-oriented documentation...

**Comment by tiborsimko** [comment]
P.S. It may be better to order columns from oldest to newest release, the x-axis being the function of time, i.e. `maint-0.7`, `maint-0.8`, ..., `master`, so that the information about the latest `master` version is displayed close to (also recent) Docs, CI, Coverage.

**Comment by mvidalgarcia** [comment]
Updated.
