### ISSUE TITLE
global: start using Dockerfile linter hadolint

### ISSUE THREAD

**Issue by audrium** [reanahub/reana#439]
Dockerfile linter called [hadolint](https://github.com/hadolint/hadolint) was introduced in this [PR](https://github.com/reanahub/reana-env-root6/pull/10) and could be propagated to all the other repositories.

It could also be configured to have a list of to-be-ignored hadolint warnings across all repositories.

P.S. There are nice wiki pages for each of the linting errors with examples and solutions how to fix it: [example here](https://github.com/hadolint/hadolint/wiki/DL3001)

P.P.S. There is also [VSCode extension](https://marketplace.visualstudio.com/items?itemName=exiasr.hadolint)

**Comment by tiborsimko** [comment]
> P.P.S. There is also VSCode extension

... as well as the full fly-checking support in Emacs and Vim obviously as well :grin:

**Comment by audrium** [comment]
Implemented with https://github.com/reanahub/reana/issues/450. Closing
