### ISSUE TITLE
ci: pin Ubuntu version in GA jobs

### ISSUE THREAD

**Issue by audrium** [reanahub/reana#454]
> BTW I noticed the following GA warning:
>`Ubuntu-latest workflows will use Ubuntu-20.04 soon. For more details, see https://github.com/actions/virtual-environments/issues/1816`
>Perhaps we should start using pinned versions to be ready fro the future. We could do this as part of hadolint/flake8 campaign...This would mean to switch from ubuntu-latest to either current ubuntu-18.04 or even better to the more forward-looking ubuntu-20.04.  

- [x] [reana-env-root6](https://github.com/reanahub/reana-env-root6/pull/12)
- [x] [docs.reana.io](https://github.com/reanahub/docs.reana.io/pull/71)
- [x] [pytest-reana](https://github.com/reanahub/pytest-reana/pull/75)
- [x] [reana](https://github.com/reanahub/reana/pull/455)
- [x] [reana-client](https://github.com/reanahub/reana-client/pull/446)
- [x] [reana-commons](https://github.com/reanahub/reana-commons/pull/237)
- [x] [reana-db](https://github.com/reanahub/reana-db/pull/114)
- [x] [reana-demo-alice-lego-train-test-run](https://github.com/reanahub/reana-demo-alice-lego-train-test-run/pull/16)
- [x] [reana-demo-atlas-recast](https://github.com/reanahub/reana-demo-atlas-recast/pull/29)
- [x] [reana-demo-bsm-search](https://github.com/reanahub/reana-demo-bsm-search/pull/23)
- [x] [reana-demo-cdci-crab-pulsar-integral-verification](https://github.com/reanahub/reana-demo-cdci-crab-pulsar-integral-verification/pull/7)
- [x] [reana-demo-cms-h4l](https://github.com/reanahub/reana-demo-cms-h4l/pull/15)
- [x] [reana-demo-helloworld](https://github.com/reanahub/reana-demo-helloworld/pull/46)
- [x] [reana-demo-root6-roofit](https://github.com/reanahub/reana-demo-root6-roofit/pull/43)
- [x] [reana-demo-worldpopulation](https://github.com/reanahub/reana-demo-worldpopulation/pull/32)

**Comment by mvidalgarcia** [comment]
Everything merged 📪
