### ISSUE TITLE
helm: configurable TTL pod behaviour

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana#461]
**Current behaviour**

REANA-Workflow-Controller uses 60 seconds default to remove finished pods:

```python
TTL_SECONDS_AFTER_FINISHED = 60
"""Threshold in seconds to clean up terminated (either Complete or Failed)
jobs."""
```

This creates troubles when investigating e.g. CERN HTCondor job submission failures, because the user runtime pods are quickly deleted.

**Expected behaviour**

It would be good to do one or more of the following:

1. In case of failures, keep the pod running and do not garbage-collect it after TTL seconds, so that admins (or user!) can inspect the error. (1a) This would also need a way to safely `kubectl delete job xxx` later (without initiating the workflow restart or some such). (1b) Or we could simply introduce two TTL values, 60 seconds default for successfully finished pods and 86400 seconds for failed pods.
2. Expose TTL value (or values) to the cluster admin, for example via Helm deployment options, so that admins can decide upon best values and eventually redeploy the cluster in times of need.
3. Expose TTL value (or values) to users, so that they can override defaults in their `reana.yaml` files as a new operational option. (This resembles the asset expiry expose task https://github.com/reanahub/reana-workflow-controller/issues/145).

**Comment by diegodelemos** [comment]
PR set ready for review, instructions on how to test [here](https://github.com/reanahub/reana/pull/484#issue-576463755).
