### ISSUE TITLE
could we rename community/cdci label to something else?

### ISSUE THREAD

**Issue by volodymyrss** [reanahub/reana#479]
Our activity has reshaped, into more international and larger project.

But "CDCI" does not apply anymore, and we decided (with @andriineronov and other colleagues) to discard the acronym to reduce confusion.

We could use "AstroODA" - this name was there since the beginning (https://www.astro.unige.ch/cdci/astrooda_/) or even just ODA - although perhaps too generic, it is also relatively unique, as far as I know.

Could you please change it?

Thanks!

**Comment by tiborsimko** [comment]
Hi @volodymyrss, renamed everywhere.

**Comment by volodymyrss** [comment]
Great, thanks!
