### ISSUE TITLE
helm: upgrade to networking.k8s.io/v1 ingress

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana#482]
Update Helm template files to fix the following warnings:

```
W0217 12:14:56.465497 1048297 warnings.go:67] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0217 12:14:56.849358 1048297 warnings.go:67] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```

Perhaps also upgrade minimal Kubernetes version to 1.14 at the same time; currently, we declare:

```
kubeVersion: ">= 1.13.0-0 < 1.21.0-0"
```

Related PRs:

- #540 (main PR with test instructions)

- https://github.com/reanahub/reana-commons/pull/299

- https://github.com/reanahub/reana-workflow-controller/pull/407

**Comment by tiborsimko** [comment]
Also seeing whilst running `reana-client run-ci`:

```
W0802 13:22:23.153278   12606 warnings.go:67] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
W0802 13:22:23.154223   12606 warnings.go:67] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0802 13:22:23.597494   12606 warnings.go:67] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
W0802 13:22:23.623856   12606 warnings.go:67] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```

The changes may be needed in quite a few places:

```console
$ rg v1beta
reana-workflow-controller/tests/test_views.py
1328:            current_k8s_networking_v1beta1=mock.DEFAULT,
1370:            current_k8s_networking_v1beta1=mock.DEFAULT,
1404:            "reana_workflow_controller.k8s" ".current_k8s_networking_v1beta1"

reana-server/reana_server/status.py
410:                "metrics.k8s.io", "v1beta1", "nodes"

reana-workflow-controller/reana_workflow_controller/k8s.py
21:    current_k8s_networking_v1beta1,
90:            api_version="networking.k8s.io/v1beta1",
307:        "ingress": current_k8s_networking_v1beta1.create_namespaced_ingress,
347:        "ingress": current_k8s_networking_v1beta1.delete_namespaced_ingress,
371:        current_k8s_networking_v1beta1.delete_namespaced_ingress(

reana/helm/reana/templates/ingress.yaml
5:apiVersion: networking.k8s.io/v1beta1
7:apiVersion: extensions/v1beta1

reana/helm/reana/templates/cronjobs.yaml
3:apiVersion: batch/v1beta1
110:apiVersion: batch/v1beta1

reana-workflow-controller/tests/test_workflow_run_manager.py
27:        current_k8s_networking_v1beta1=DEFAULT,
40:            "current_k8s_networking_v1beta1"
54:        current_k8s_networking_v1beta1=DEFAULT,
81:        current_k8s_networking_v1beta1=DEFAULT,
93:                "current_k8s_networking_v1beta1"
127:        current_k8s_networking_v1beta1=DEFAULT,

reana-commons/reana_commons/k8s/api_client.py
45:    if api == "extensions/v1beta1":
53:    elif api == "networking.k8s.io/v1beta1":
64:current_k8s_networking_v1beta1 = LocalProxy(
65:    partial(create_api_client, api="networking.k8s.io/v1beta1")
```

**Comment by tiborsimko** [comment]
How to test this easily:

- using last official Kind release (0.11.1), everything works fine
- using latest Kind development version [from sources](https://github.com/kubernetes-sigs/kind) installed via `make build`, you should see that REANA is not deployable there anymore due to the above v1beta1 and friends
- MVP goal is to replace `extensions/v1beta1` everywhere so that REANA would work on Kubernetes 1.22; you can develop on any Kind, but using Kind `master` would show the error easily
- beyond MVP goal is to fix also `batch/v1beta1` but this can in theory wait for Kubernetes 1.25 so we'd have time for this
- beware of `if api else api` in `r-commons` as seen above
- the changes should be tested not only for deployment, but also for running all workflows, and for spawning interactive sessions (jupyter notebooks) which will show the effects from `r-commons`

**Comment by VMois** [comment]
1. In addition to `ingress.yaml`, we will need to upgrade `traefik` to version `10.0.0+` if we want to support Kubernetes `1.22+`. Currently, `traefik` version is 1.85.x (very old, from obsolete Helm chart repo) and can support Kubernetes up to `1.21` ([source](https://artifacthub.io/packages/helm/traefik/traefik#kubernetes-version-support)). If we will upgrade to `traefik 10.0+`, we will not support Kubernetes `=<1.15`, which looks fine be me.

**Comment by VMois** [comment]
@tiborsimko do we want to keep support for `networking.k8s.io/v1beta1`?

**Comment by tiborsimko** [comment]
> @tiborsimko do we want to keep support for `networking.k8s.io/v1beta1`?

We don't have to keep that support if we upgrade the declaration of the minimally-required Kubernetes version if the Helm charts....

**Comment by VMois** [comment]
In addition, we will need to upgrade the `python-kubernetes` client. The current version (11.x) doesn't have, for example, `NetworkingApiV1.delete_namespaced_ingress` method (`extensions` and `v1beta` has). The latest released stable version `18.x` [doesn't have it](https://github.com/kubernetes-client/python/blob/release-18.0/kubernetes/docs/NetworkingV1Api.md) either. Only starting from version `19.x`, `delete_namespaced_ingress` will be added to  ([source](https://github.com/kubernetes-client/python/blob/release-19.0/kubernetes/docs/NetworkingV1Api.md)). There is alpha version of `19.x`

**Comment by mvidalgarcia** [comment]
What's the status of this task? Shall we try to merge it or close it? cc/ @tiborsimko
