### ISSUE TITLE
RFC {hub, ghi} -> gh

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana#483]
**Current status**

We are using `hub` command-line tool to interact with GitHub, see:

```console
$ rg 'hub '
reana/reana_dev/git.py
1192:            "hub pull-request -p --no-edit",
1193:            "hub pr list -L 1",
```

In addition, I have been using `ghi` command line tool to interact with GitHub labels, for example:

```console
$ ghi label "compute/htcondor" -c 82ff35
```

**Local status**

Personally I have switched locally to using the new `gh` command-line tool to interact with GitHub for everything this week. It replaces both `hub` and `ghi` tools for me.

For example, to view pull requests in a browser for a repository, one can do:

```console
$ gh pr list -w   # equivalent to the old `hub browse -- pulls`
```

For example, to work with labels, one can do things like:

```bash
for repo in $(ls -1); do
    cd $repo
    (gh api "repos/:owner/:repo/labels/community/cdci" && \
     gh api "repos/:owner/:repo/labels/community/cdci" -f new_name=community/astrooda)
    cd ..
done
```

**Proposal**

Are we OK to replace `hub` and `ghi` fully from the REANA code base and in our personal workflows everywhere?  

If so, this would also open a possibility to use `gh` internally in `reana-dev git-fork` and `reana-dev git-clone` to fully automatise commands. 

Yay or nay?

**Comment by mvidalgarcia** [comment]
A big yay from my side. I've been using `gh` for several months now and it works pretty well.

**Comment by ParthS007** [comment]
Yay. I tried it recently and It works fine.

**Comment by tiborsimko** [comment]
In addition, we can try to simplify the repository forking process that currently is semi-automated:

```console
$ reana-dev --help
...
  How to fork and clone all REANA repositories:

  .. code-block:: console

          $ reana-dev git-fork -c ALL
          $ eval "$(reana-dev git-fork -c ALL)"
          $ reana-dev git-clone -c ALL -u tiborsimko
```

The `git-fork` opens a lot of browser tabs one needs to click on to confirm the forking. It would be better if we could do all the work automatically using `gh api` for forking.  (Similarly as I'm using `gh api` for label management described above.)
