### ISSUE TITLE
cli: `--check-only` to show full test matrix status by snapshots

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana#489]
When `--check-only` is used, it would be good not to loop over statuses, as currently happens:

```console
$ reana-dev run-example -c DEMO -b kubernetes -b htcondorcern -b slurmcern --check-only 
[2021-03-16T19:30:02] : Running the following matrix:
Demos: reana-demo-root6-roofit,reana-demo-atlas-recast,reana-demo-helloworld,reana-demo-worldpopulation
Workflow engines: cwl,serial,yadage
Compute backends: htcondorcern,slurmcern,kubernetes
[2021-03-16T19:30:07] reana-demo-root6-roofit: reana-client status -w root6-roofit-cwl-htcondorcern
NAME                            RUN_NUMBER   CREATED               STARTED               STATUS    PROGRESS
root6-roofit-cwl-htcondorcern   1            2021-03-16T18:27:58   2021-03-16T18:28:00   running   0/2     
[2021-03-16T19:30:13] reana-demo-root6-roofit: reana-client status -w root6-roofit-cwl-htcondorcern
NAME                            RUN_NUMBER   CREATED               STARTED               STATUS    PROGRESS
root6-roofit-cwl-htcondorcern   1            2021-03-16T18:27:58   2021-03-16T18:28:00   running   0/2     
...
```

but rather print the current status, so that the person running the test suite could take a "snapshot" of the current state.

IOW, in the sequential mode, we want to wait until the end of the loop for each job, and move on to the next job; but in the parallel test mode, we are interested in seeing the snapshot at some moment in time of everything that is running, without waiting for anything, and then to retake that same snapshot 15 minutes later, 30 minutes later, etc.

Can we amend not to do status sleep while doing for the `--check-only` view of the results?

BTW, this also means not to stop after failures:

```console
$ reana-dev run-example -c DEMO -b kubernetes -b htcondorcern -b slurmcern --check-only
...
[2021-03-16T20:00:28] reana-demo-root6-roofit: Command 'reana-client logs -w root6-roofit-cwl-htcondorcern | grep -c 'RooChebychev::bkg'' returned non-zero exit status 1.
```

but rather continue making the "snapshot" of the test cases, and then finish with some mini-report like:

```console
[2021-03-16T20:02:27] reana-dev run-example demo summary:
- 29 demo workflows run
- 27 passed
- 2 failed (foo-cwl-slurmcern, bar-yadage-kubernetes)
```

_Originally posted by @tiborsimko in https://github.com/reanahub/reana/pull/487#discussion_r595442578_

**Comment by VMois** [comment]
So, to confirm what is expected at the end. With new changes `--check-only` will return results as below:

```bash
$ reana-dev run-example -c DEMO --check-only
[2021-03-16T20:02:27] reana-dev run-example demo summary:
- 29 workflows running
- 27 passed
- 2 failed (foo-cwl-slurmcern, bar-yadage-kubernetes)

$ # notice, no waiting for results
```
