### ISSUE TITLE
mq: make message queue persistent and resilient

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana#500]
Current message queue is subject to lose workflow submissions in the event of message broker getting restarted/relocated:

Plan:
- Investigate how to persist the RabbitMQ queue, e.g. https://www.rabbitmq.com/persistence-conf.html
- Test disaster recovery mode, i.e. what happens if we abruptly kill the RabbitMQ instance? e.g. `kubectl delete pod reana-message-broker-xxxxx-yyyy-zzz`

**Comment by ParthS007** [comment]
Reference Links:

- https://www.rabbitmq.com/persistence-conf.html
- https://www.cloudamqp.com/blog/how-to-persist-messages-during-RabbitMQ-broker-restart.html
- https://kousiknath.medium.com/dabbling-around-rabbit-mq-persistence-durability-message-routing-f4efc696098c
