### ISSUE TITLE
reana-dev helm-upgrade-components should also update prefetch-images script

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana#515]
`reana-dev helm-upgrade-components` currently updates `helm/reana/values.yaml` file. For example, it replaces images:

```diff
     docs_url: http://docs.reana.io
     forum_url: https://forum.reana.io
     imagePullPolicy: IfNotPresent
-    image: reanahub/reana-ui:0.8.0-alpha.1
+    image: reanahub/reana-ui:0.8.0-alpha.2
```

It should also update `scripts/prefetch-images.sh` where these images are pre-fetched.

**Comment by VMois** [comment]
I can see that `prefetch-images.sh` is only used on one page, in one part in `docs.reana.io`. Do we really need it? I believe, helm (or kind) can fetch those images without a problem.

If it is really that necessary to maintain this file, I would prefer to fetch values from `values.yml` and generate a new `bash` from this. This will ensure better consistency.

**Comment by mvidalgarcia** [comment]
It's also referenced in www.reana.io as part of the _Get started_ section.

Check this [commit](https://github.com/reanahub/reana/commit/c3f665891c66bd9b516edaf7cbbc0db2dd174e75#diff-7307c9701a03fb91cef51859dea17d269752215eaca7c96a6a97a96dc54259d7) and the [issue](https://github.com/reanahub/reana/issues/431) it closes.
