### ISSUE TITLE
release: 0.7.4 

### ISSUE THREAD

**Issue by audrium** [reanahub/reana#519]
Shared components:
 - [x] pytest-reana (0.7.2, @audrium): https://github.com/reanahub/pytest-reana/pull/84
 - [x] reana-commons (0.7.5, @audrium): https://github.com/reanahub/reana-commons/pull/274

Cluster components:
- [x] reana-job-controller (0.7.5, @audrium): https://github.com/reanahub/reana-job-controller/pull/319
- [x] reana-workflow-engine-cwl (0.7.6, @audrium): https://github.com/reanahub/reana-workflow-engine-cwl/pull/189
- [x] reana-workflow-engine-yadage (0.7.5, @audrium): https://github.com/reanahub/reana-workflow-engine-yadage/pull/195
- [x] reana-workflow-engine-serial (0.7.5, @audrium): https://github.com/reanahub/reana-workflow-engine-serial/pull/146
- [x] reana-workflow-controller (0.7.4, @audrium): https://github.com/reanahub/reana-workflow-controller/pull/387
- [x] reana-server (0.7.6, @audrium): https://github.com/reanahub/reana-server/pull/387

Client components:
- [x] reana-client (0.7.5, @audrium): https://github.com/reanahub/reana-client/pull/532

Helm chart:
- [x] reana (0.7.4, @audrium): https://github.com/reanahub/reana/pull/521

Docs:
- [x] www.reana.io update: https://github.com/reanahub/www.reana.io/pull/65
- [x] blog post: https://github.com/reanahub/blog.reana.io/pull/13

**Comment by tiborsimko** [comment]
Everything was merged, released and published  in respective PRs.
