### ISSUE TITLE
Merge maint-0.7 to master

### ISSUE THREAD

**Issue by audrium** [reanahub/reana#524]
Recipe: https://github.com/reanahub/reana/issues/480
0.7.4 release issue: https://github.com/reanahub/reana/issues/519

- [x] pytest-reana: https://github.com/reanahub/pytest-reana/pull/85
- [x] reana-commons: https://github.com/reanahub/reana-commons/pull/276
- [x] ~reana-db~ (no changes)
- [x] reana-job-controller: https://github.com/reanahub/reana-job-controller/pull/320
- [x] ~reana-message-broker~ (no changes)
- [x] ~reana-ui~ (no changes)
- [x] reana-server: https://github.com/reanahub/reana-server/pull/389
- [x] reana-workflow-controller: https://github.com/reanahub/reana-workflow-controller/pull/388
- [x] r-w-e-cwl: https://github.com/reanahub/reana-workflow-engine-cwl/pull/191
- [x] r-w-e-serial: https://github.com/reanahub/reana-workflow-engine-serial/pull/148
- [x] r-w-e-yadage: https://github.com/reanahub/reana-workflow-engine-yadage/pull/197
- [x] reana-client: https://github.com/reanahub/reana-client/pull/535
- [x] reana: https://github.com/reanahub/reana/pull/525

**Comment by tiborsimko** [comment]
Everything working locally, checked and merged.
