### ISSUE TITLE
sprint: Internal-Consolidation kick-off

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana#55]
# Internal-Consolidation sprint kick-off

### Dates

- **2018-04-18** kick-off
- **2018-05-02** closure

### People

- @diegodelemos (~5d) 
- @dinosk (~10d) 
- @tiborsimko (~10d)

### Goals

Consolidate the REANA internals and the collaboration between components. Separate DB into a real service. Share models and schemas across the ecosystem. Improve logging and traceback propagation. Introduce simple serial workflow engine. Prepare basic CI.

### Planning

![internal-consolidation](https://user-images.githubusercontent.com/517546/38941721-792f4d64-432d-11e8-97f6-7cd7059d5f49.png)

### Kanban

- kanban board https://waffle.io/reanahub/reana?milestone=Internal-Consolidation

**Comment by diegodelemos** [comment]
✔️ Consolidate the REANA internals and the collaboration between components. 
✔️ Separate DB into a real service.
✔️ Share models and schemas across the ecosystem.
➖ Improve logging and traceback propagation.
✔️ Introduce simple serial workflow engine. 
➖ Prepare basic CI.

Next milestone [0.3.0](https://waffle.io/reanahub/reana?milestone=0.3.0).
