### ISSUE TITLE
benchmark: allow submission by other means

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana#572]
**Current behaviour**

For pMSSM NoSys tests: 

- The workflows were submitted using `recast submit` tool, which required a little modification to (i) set desired workflow name and (ii) only create and upload, not start.

- The workflows were started using `reana_bench` script, which required a little modification to not create, not upload, and not check for existence, only start workflows.

Here is the quick diff to the bench script:

```diff
@@ -62,6 +62,7 @@


 def _create_workflow(workflow: str, file: str) -> None:
+    return
     reana_specification = load_reana_spec(
         click.format_filename(file),
         access_token=REANA_ACCESS_TOKEN,
@@ -71,6 +72,7 @@


 def _upload_workflow(workflow: str) -> None:
+    return
     upload_cmd = _build_command("upload", workflow)
     subprocess.run(upload_cmd, stdout=subprocess.DEVNULL)

@@ -343,7 +345,7 @@
 def _start_benchmark(
     workflow_name: str, number_of_submissions: int, file: str, workers: int
 ) -> pd.DataFrame:
-    if _workflow_already_exists(workflow_name):
+    if False and _workflow_already_exists(workflow_name):
         raise Exception("Found duplicated workflow name. Please use unique name.")

     _create_and_upload_workflows(workflow_name, number_of_submissions, file, workers)
```

This worked well and allowed pMSSM benchmarking easily.

**Expected behaviour**

We can make this configurable so that no script modification would be necessary. 

The main idea is that we should not assume that the benchmarking tool will be the one always doing everything, from workflow creation to workflow launch.  IOW, currently, `launch = create + upload + start`, and we should allow that some of these steps are done using outside tools.

As an illustration, we could do one of the following:

1. Keep `launch` command and introduce new options `launch --create-only`, `launch --upload-only`, `launch --start-only`.

2. Drop `launch` command and separate it into `create`, `upload`, and `start` commands that will be launched by the user one after another.  (We could later have a `run` command wrapper that does everything.)  And, in the pMSSM case, the create/upload pair would be executed by another tool.

3. Notiing that having separate create and separate upload steps does not perhaps makes too much sense, as it'll be usually one single tool that will be "preparing" workflows for running (by creating them and uploading files), and another tool that will start them and measure performance, we could perhaps introduce only two new steps, `submit` (doing create+upload) and `start` (doing start.)

**Comment by VMois** [comment]
I would go with *2* and *3* so having `submit` (create + upload) and `start` commands, but leave `launch` to do `submit` + `start` together (basically as it is now).
