### ISSUE TITLE
0.8.0-alpha.5

### ISSUE THREAD

**Issue by audrium** [reanahub/reana#580]
Prepare 0.8.0-alpha.5 release PRs.

For each component, check whether everything from `maint-0.7` was integrated (using `git log master..maint-0.7`).

Test integration on many examples before merging and pushing images:
- [x] Kubernetes (tested all demos)

Test HTCondor/Slurm compute backends again:
- [x] HTCondor (tested helloworld)
- [ ] Slurm (tested roofit demo)

Shared components:
- [x] pytest-reana - No PR needed, only copyright fixes after release (reanahub/pytest-reana@cf9e27a)
- [x] reana-commons (https://github.com/reanahub/reana-commons/pull/316)
- [x] reana-db (https://github.com/reanahub/reana-db/pull/153)

Cluster components:
- [x] reana-job-controller (https://github.com/reanahub/reana-job-controller/pull/344)
  - 🐳 [reanahub/reana-job-controller:0.8.0-alpha.7](https://hub.docker.com/layers/reanahub/reana-job-controller/0.8.0-alpha.7/images/sha256-af56eba82b1f1b6f1b495327f6a1d4205b3bd4feba84febb9c624a0a69a08aff?context=explore)
  - 🐳 [reanahub/reana-job-controller-htcondorcern-slurmcern:0.8.0-alpha.7](https://hub.docker.com/layers/reanahub/reana-job-controller-htcondorcern-slurmcern/0.8.0-alpha.7/images/sha256-02faa2fbb2bddb146059e0aae260894484ec417b171161b6967de51b8f41a6b6?context=explore)
- [x] reana-message-broker- No PR needed, only copyright fixes after release
- [x] reana-server (https://github.com/reanahub/reana-server/pull/416)
  - 🐳 [reanahub/reana-server:0.8.0-alpha.6](https://hub.docker.com/layers/reanahub/reana-server/0.8.0-alpha.6/images/sha256-1e172dd9a269e4d30313b80a2dacc92f28287c66c402952569b8bf7aaaaa2feb?context=explore)
- [x] reana-ui (https://github.com/reanahub/reana-ui/pull/201)
  - 🐳 [reanahub/reana-ui:0.8.0-alpha.4](https://hub.docker.com/layers/reanahub/reana-ui/0.8.0-alpha.4/images/sha256-0d65948da29fd20ee82259f7c0a9f9ebc34f0c6a87ce28b3b992dae3b4ab9f2f?context=explore)
- [x] reana-workflow-controller (https://github.com/reanahub/reana-workflow-controller/pull/420)
  - 🐳 [reanahub/reana-workflow-controller:0.8.0-alpha.5](https://hub.docker.com/layers/reanahub/reana-workflow-controller/0.8.0-alpha.5/images)
- [x] reana-workflow-engine-cwl - No PR needed, only copyright fixes after release
- [x] reana-workflow-engine-serial - No PR needed, only copyright fixes after release
- [x] reana-workflow-engine-snakemake - No PR needed, only copyright fixes after release
- [x] reana-workflow-engine-yadage (https://github.com/reanahub/reana-workflow-engine-yadage/pull/214)
  - 🐳 [reanahub/reana-workflow-engine-yadage:0.8.0-alpha.5](https://hub.docker.com/layers/reanahub/reana-workflow-engine-yadage/0.8.0-alpha.5/images/sha256-5465d6d0ee138b9ca7b8b9bab5f368bf6b7043cd1b71b213ef7a7208fcf15526?context=explore)  

Client components:
- [x] reana-client (https://github.com/reanahub/reana-client/pull/578)

Helm chart:
- [x] reana (https://github.com/reanahub/reana/pull/586)
- [ ] test researcher-oriented helm installation method.

**Comment by mvidalgarcia** [comment]
Deployed on DEV, QA and reana21. Slurm to be checked in a different issue.
