### ISSUE TITLE
benchmark: harmonise status colours across the plot

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana#588]
It'll be good to harmonise plot colours across the produced set.

**Example 1:** The "pending" status is orange in execution progress plot, but "blue" in histogram of pending times.

Using similar colours may facilitate recognition over various plots.

**Example 2:** Sometimes workflows are failing, such as here:

![susy201816-submit200-sleep0-total200_execution_status_1_200](https://user-images.githubusercontent.com/517546/141470446-76ba7e7f-9fa9-435f-9862-d55a89a20442.png)

but this is not visible in the progress plot:

![susy201816-submit200-sleep0-total200_execution_progress_1_200](https://user-images.githubusercontent.com/517546/141470527-ccdbc881-3273-4e63-b7be-362bfa694da1.png)

It would be good to colour those that fail differently, e.g. in red. Dunno though whether these can be easily seen amongst the sea of blue ones that finished well -- but it would be useful for "zooming in", that is when plotting only results since time T1 until time T2.

**Example 3:** During long-running tests, such as 100k pMSSM NoSys, it'll be useful to make several "snapshots" as the tests progress. So there will be "finished" workflows, "running" workflows, "pending" workflows, "failed" workflows, etc.  It'll be useful to indicate via different colours in the progress plot where we stand.

Could we come up with a consistent colour scheme, e.g. done=green, running=blue, pending=orange, and apply it everywhere across all  the various plots in the consistent manner?

For fun, here is one "colourful" diagram from past tests, showing various statuses appearing along:
![pMSSM-NoSys-1200Mi-10nodeb-65nodej-145max_execution_status](https://user-images.githubusercontent.com/517546/141471118-32c80643-171f-470b-8470-ae5b2018b4b2.png)

**Comment by VMois** [comment]
How should we distinguish between `queued` and `pending` statuses in terms of color? (more related to `execution_status` plot)

In addition, `execution_progress` plot treats those two statuses + time until `started` as `pending` time together. Is it important for us to distinguish it? If yes, it can be a new issue to do later.

**Comment by VMois** [comment]
Was not sure how to represent execution progress or colors, here is a possible solution I came up with:

![color_execution_progress_1_46](https://user-images.githubusercontent.com/15694232/142211650-86049387-6837-40d6-b5a6-8a3c4266b81b.png)

![color_execution_progress_1_2000](https://user-images.githubusercontent.com/15694232/142211406-b62f264f-48a5-4056-b2fc-7ed06530fb8d.png)

![color_execution_status_1_2000](https://user-images.githubusercontent.com/15694232/142211463-1a2d3159-20cb-49d0-82e7-80b453d1ee80.png)

- renamed `pending` to `awaiting run`, the reason explained in the 2nd point above. There could be multiple statuses inside the "pending" line, like `pending`, `queued`, or even `created`

- removed `started` point as it is clear from `awaiting` and `running` lines where workflow started (can be returned back, but needs a nice color)

- points at the end represent a status of a workflow. reason: having the whole red line to indicate that workflow failed (or finished) is a bit misleading in my opinion. On the other side, points are not as visible.

P.S Histograms are not yet ready.
