### ISSUE TITLE
benchmark: single x-axis tick

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana#590]
Sometimes, when workflows run fast, the x-axis has only one label, which is not enough to judge about the runtimes :wink: 

![roofit-1i-32b-134j-submit200-sleep0-total200-run20211116k_execution_progress_1_200](https://user-images.githubusercontent.com/517546/142038249-99813b23-8e25-4eed-9aaa-fb26fb96cc7c.png)

![roofit-1i-32b-134j-submit200-sleep0-total200-run20211116k_histogram_runtime_1_200](https://user-images.githubusercontent.com/517546/142038242-e8f3a530-a7de-4afa-983b-e968ae1b2bd2.png)

**Comment by VMois** [comment]
Have you used `-i 1` (interval of 1 minute for the plot) in `analyze` command? Default is 10 minutes and, indeed, it is not good for fast-running workflows.

**Comment by tiborsimko** [comment]
Haven't set the interval manually... The issue is more about auto-discovering appropriate size in the default mode, e.g. what about checking max value and min value and divide in about ten bin and then round to some human-friendly amount, be it 10 seconds, 30 seconds, 1 minute, 5 minute, 10 minute, etc automatically?

**Comment by VMois** [comment]
I would prefer to keep manual intervals and, maybe, extend them (`-i 1m` - 1 minute, `-i 30s` - 30 seconds, etc.) in the future. But automatic discovery can be also done if you want to - your decision here.

In case we go with automatic discovery:

1. Do we keep the manual `-i` option or remove it?

2. Should the number of bins be a constant like `10`? The number of bins is determined by how many can fit into the plot so it is probably some sort of constant if the size of the plot doesn't change.

**Comment by tiborsimko** [comment]
WRT 1, automatic is better, and keeping `-i` for users so that they will be able to override the automatic defaults. This is basically how plotting tools work, e.g. try `gnuplot` and `plot sin(x)`: if you don't specify axis intervals, some "automatic" ones are selected by the tool, so that the graph will be readable. But you can always overrride by specifying your own axis values and intervals.

WRT 2, it could be 5 if 10 is too much; anything aesthetically pleasing will do. Basically, if you discover that the test took 10 minutes, the suitable interval could be 2 minutes, and if it took 10 seconds, the suitable interval could be 2 seconds, so that there is always "about five" ticks on the time axis. Simplifies reading.

(This is all just cosmetics so that the plots would come out nicely "by default"...)
