### ISSUE TITLE
cli: richer `reana-dev run-example -c DEMO` example set

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana#633]
Enrich a list of runnable demo examples so that the command `reana-dev run-example -c DEMO` would more completely test the ones we now are working well

This requires to amend `REPO_LIST_DEMO_RUNNABLE` and add the following ones:

- reana-demo-alice-lego-train-test-run
- reana-demo-alice-pt-analysis
- reana-demo-bsm-search
- reana-demo-cms-h4l 
- reana-demo-cms-dimuon-mass-spectrum

Some challenges:

- e.g. BSM uses `reana.yaml` but it is Yadage, so it requires similar change as atlas recast example when generating appropriate workflow name;
- e.g. CMS H4L only works well for Snakemake, so use only this example for now (we have an issue for fixing CWL there);
- don't forget to change `EXAMPLE_OUTPUT_FILENAMES` and `EXAMPLE_LOG_MESSAGES` for output checking. The log messages and output files to check for should be "unique enough" to make sure that it works well;
- don't forget to identify which images to pre-fetch in `DOCKER_PREFETCH_IMAGES`.

The ultimate goal is that `reana-dev run-example -c DEMO` will run virtually all of our examples (=hence slow, but exhaustive) so that it can provide complete testing matrix for nightly integrations etc. Whilst individual developers could still use `reana-dev run-example -c .` or `reana-dev run-example -c r-d-helloworld` to run only individual examples (=hence fast, but less covering) when developing some novel workflow features.

**Comment by tiborsimko** [comment]
... and, as our test matrix of demo examples grows, it'll be good to finally address this one https://github.com/reanahub/reana/issues/489 after addressing the current issue.

**Comment by VMois** [comment]
The same happens with `reana-demo-alice-lego-train-test-run`. Delay in getting final files. Plus, I saw that workflow was reported as `finished` but job logs were showing that the last job is still running.

**Comment by tiborsimko** [comment]
Hmm, a few minutes for files to appear? That sounds like quite a long wait... Does this happen only locally or also in PROD? 

Two more thoughts:

- Perhaps remove `tee` commands for simplicity? We have a ticket about that, see https://github.com/reanahub/reana/issues/264. But I don't think `tee`-ing would cause any such huge delays; it should be fast. (and is part of the job anyway)
- Perhaps just look at the existence of temporary files created in the before-last step? (as a temporary workaround)

**Comment by VMois** [comment]
> Does this happen only locally or also in PROD?

PROD

**Comment by VMois** [comment]
I can see that logs are also affected sometimes. So, it can fail from temporary missing files or logs. Increasing the `timecheck` parameter might help to reduce possible fails, I guess.

**Comment by VMois** [comment]
Regarding the issue with logs. Looks like the `TIMEOUT` constant that restricts runtime to 5 minutes, might trigger the error. I will try with a default of 15 minutes.
