### ISSUE TITLE
How to manage local users?

### ISSUE THREAD

**Issue by arm2arm** [reanahub/reana#668]
Hello,
I can add and activate users using  **flask reana-admin** tool but cannot  edit or delete users. How to do that in the local deployments? : 
Current 0.8.4 Documentation stating it is not possible:
```
Usage: flask reana-admin [OPTIONS] COMMAND [ARGS]...

  REANA administration commands.

Options:
  --help  Show this message and exit.

Commands:
  create-admin-user         Create default user.
  quota-resources           List available quota resources.
  quota-set                 Set quota limits to the given users per...
  quota-set-default-limits  Set default quota limits to users that do not...
  quota-usage               List quota usage of users.
  status-report             Get a status report of the REANA system.
  token-grant               Grant a token to the selected user.
  token-revoke              Revoke selected user's token.
  user-create               Create a new user.
  user-export               Export all users in current REANA cluster.
  user-import               Import users from file.
  user-list                 List users according to the search criteria.

``` 
thank you beforehand.

**Comment by tiborsimko** [comment]
Hi @arm2arm, REANA indeed does not allow currently to edit or delete users.  The closest you can do right now is to revoke a token from a user using the `token-revoke` command, which will prevent the user from starting new workflows.

WRT editing, what would be the concrete use case? E.g. amend the email address of the user after changing institutions? 

WRT deleting, the full account deletion may be tricky, as you may want to delete also the user workflows' workspaces whilst still keeping some CPU quota usage information for resource accounting (if enabled). So we cannot simply hard-delete some database rows; rather we may want to soft-delete the user by special account status tagging.

We could plan the implementation for some of the above functionality, if interested.

**Comment by arm2arm** [comment]
thank you! well done 👏
