### ISSUE TITLE
Creation of reana-db

### ISSUE THREAD

**Issue by dinosk** [reanahub/reana#71]
Currently, reana-commons contains the db models and Session handling. For this reason it could not be included in the workflow engines. A stand alone repository `reana-db` can be created to host all db related code (and alembic recipes in the future), allowing to merge reana-workflow-commons and reana-commons.

**Comment by tiborsimko** [comment]
Repository created, RTFD configured, Travis CI to follow.

Keeping this issue open because we have to add the module to `docs/administratorguide.rst` once the initial module skeleton will be there. (see https://github.com/reanahub/reana-db/issues/1)

**Comment by diegodelemos** [comment]
Closed by:
https://github.com/reanahub/reana-db/pull/4
https://github.com/reanahub/reana-commons/pull/35
https://github.com/reanahub/reana-server/pull/76
https://github.com/reanahub/reana-workflow-controller/pull/117
https://github.com/reanahub/reana-job-controller/pull/80
