### ISSUE TITLE
interactive jupyter sessions doesn't contain secrets 

### ISSUE THREAD

**Issue by arm2arm** [reanahub/reana#805]
Hello everybody, 
we are struggling with the following trouble:
* store some secrets using the reana-client,  for example: TOKEN
* run a workflow: works, env got variable 
problem:
* start  interactive session
* in the terminal env doesn't show the TOKEN variable.
it seems all secrets are not  propagate to interactive sessions. 
how we can fix this?
thank you beforehand.

**Comment by mdonadoni** [comment]
Hello Arman,
I've checked the code and indeed REANA is not propagating any secret to interactive sessions.
However, we can implement this in one of the next REANA versions. I'm adding this to our "to do" list.
