### ISSUE TITLE
launch URL is beheaving wrong on gitlab instance, but not on github.

### ISSUE THREAD

**Issue by arm2arm** [reanahub/reana#844]
Dear Developers, we have following problem: same reana.yaml doesnot run hosted on different git repos.

1)  URL giving error: An error has occurred Cannot handle given URL
https://reanadev2.aip.de:30443/launch?url=https://gitlab.aip.de/akhalatyan/reanademo 
same error with branches:
https://reanadev2.aip.de:30443/launch?url=https://gitlab.aip.de/akhalatyan/reanademo/-/tree/tester
but URL: https://reanadev2.aip.de:30443/launch?url=https://gitlab.aip.de/akhalatyan/reanademo.git
running as expected.
---
digging more in logs we can see: 
```
2024-11-11 16:06:58,648 | root | uWSGIWorker4Core3 | ERROR | Traceback (most recent call last):
  File "/code/./reana_server/rest/launch.py", line 167, in launch
    fetcher = get_fetcher(url, tmpdir, specification)
  File "/code/./reana_server/fetcher.py", line 514, in get_fetcher
    raise ValueError("Cannot handle given URL")
ValueError: Cannot handle given URL
```
2)  the same reana.yaml hosted on github.com working without problems with tree or commint hash 
Works as expected: https://reanadev2.aip.de:30443/launch?url=https://github.com/arm2arm/reana-demo/tree/tester

current server image: reanahub/reana-server:0.9.5-alpha.2

Any assistance would be greatly appreciated. Thank you!

**Comment by mdonadoni** [comment]
Hello @arm2arm ,

The GitLab instances allowed to be used with the launcher are:
- gitlab.com
- gitlab.cern.ch
- the instance set as `secrets.gitlab.REANA_GITLAB_HOST`

What value is set as  `secrets.gitlab.REANA_GITLAB_HOST` in the Helm values? Could you double check whether it is set to `gitlab.aip.de`?

Question: do you need to support **more than one** additional GitLab instances, other than gitlab.com and gitlab.cern.ch?

**Comment by mdonadoni** [comment]
Related issue: https://github.com/reanahub/reana-server/issues/603

**Comment by arm2arm** [comment]
Fixed with one git url working as expected, thank you.
