### ISSUE TITLE
RFC  license change

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana#86]
In order to facilitate collaboration with external non-GPL licensed systems, we consider changing the  REANA platform license from GNU GPL to a more permissive MIT License. 

According to the change log, here is the full list of authors and contributors:

- [x] Alexander Baranov (@sashabaranov)
- [x] Anton Khodak @anton-khodak 
- [x] Diego Rodriguez @diegodelemos 
- [x] Dinos Kousidis @dinosk 
- [x] Harri Hirvonsalo @hjhsalo 
- [x] Lukas Heinrich @lukasheinrich 
- [x] Michael R. Crusoe @mr-c 
- [x] Sinclert Perez @Sinclert 
- [x] Tibor Simko @tiborsimko

Can we please all explicitly express our agreement/disagreement?

**Comment by tiborsimko** [comment]
P.S. See also @sashabaranov's past one-line documentation fix and contribution license statement at https://github.com/reanahub/reana/pull/47

**Comment by tiborsimko** [comment]
Tibor Simko (@tiborsimko) agrees with the license change to the MIT License.

**Comment by mr-c** [comment]
Michael R. Crusoe (@mrc) agrees with the license change to the MIT License.

Though it would be nice if the CWL parts were Apache-2.0 licensed. I agree to that as well.

**Comment by dinosk** [comment]
Dinos Kousidis (@dinosk) agrees with with the license change to the MIT License.

**Comment by diegodelemos** [comment]
Diego Rodríguez Rodríguez (@diegodelemos) agrees with the license change to the MIT License.

**Comment by sashabaranov** [comment]
Alexander Baranov (@sashabaranov) agrees with the license change to the MIT License.

**Comment by anton-khodak** [comment]
Anton Khodak (@anton-khodak) agrees with the license change to the MIT License.

**Comment by Sinclert** [comment]
Sinclert Pérez (@Sinclert) agrees with the license change to the MIT License.

**Comment by hjhsalo** [comment]
Harri Hirvonsalo (@hjhsalo) agrees with the license change to the MIT License.

**Comment by lukasheinrich** [comment]
Lukas Heinrich (@lukasheinrich ) agrees with the license change to the MIT License.

**Comment by tiborsimko** [comment]
Closing as agreed; implementation starts separately in every repository.
